### ISSUE TITLE
Add meta and link tags for social media and icons

### ISSUE THREAD

**Issue by cliftondavies** [cliftondavies/Hikes-Against-Poverty#9]

**Comment by theprogrammerinyou** [comment]
Can you please explain the task so that I can be of some help.

**Comment by cliftondavies** [comment]
Hi @theprogrammerinyou. Thanks for your interest, however, I am closing this issue.

Check out this [article](https://www.matuzo.at/blog/html-boilerplate/) for background information on what the issue was related to.
